name: Scala/C++ CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  small-designs:
    runs-on: ubuntu-slim

    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M

    steps:
      - name: checkout essent & firrtl-sig
        uses: actions/checkout@v6
        with:
            submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: build
        run: sbt compile

      - name: run small designs
        run: sbt 'run all'
